config/routes.rb
Rails.application.routes.draw do

  resources :dealerships do
    resources :cars do
      member do
        post :create_comment
        delete :delete_comment
      end
    end

    member do
      post :create_comment
      delete :delete_comment
    end
  end

  root 'welcome#index'

end

app/models/car.rb
class Car < ActiveRecord::Base

  belongs_to :dealership
  has_many :comments, as: :commentable

  include Workflow
  workflow do
    state :for_sale do
      event :reserve, transitions_to: :reserved
      event :sell, transitions_to: :sold
    end
    state :reserved do
      event :reneg, transitions_to: :for_sale
      event :sell, transitions_to: :sold
    end
    state :sold
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

app/models/dealership.rb
class Dealership < ActiveRecord::Base
  has_many :cars#, dependent: :destroy
  has_many :comments, as: :commentable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy, :sell_car, :reserve, :reneg]

  # before_action :set_dealership

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
    @dealership = Dealership.find params[:dealership_id]
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    p '*'*100
    p params
    @dealership = Dealership.find params[:dealership_id]
    @comment = @car.comments.new
  end

  # GET /cars/new
  def new
    @car = Car.new
    @dealership = Dealership.find params[:dealership_id]
  end

  # GET /cars/1/edit
  def edit
    @dealership = Dealership.find params[:dealership_id]
  end

  # POST /cars
  # POST /cars.json
  def create
    
    @dealership = Dealership.find params[:dealership_id]
    # This will create a new car object OFF OF THE DEALERSHIP. So it will create the relationship between the two.
    # Car.new({make: "Honda", dealership_id: @dealership.id})
    @car = @dealership.cars.new(car_params)
    # p @dealership.cars
    respond_to do |format|
      if @car.save
        flash[:notice] = "Car was successfully created"
        format.html { redirect_to dealership_path(@dealership) }
      else
        flash[:error] = "Car was not successfully created"
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    @dealership = Dealership.find params[:dealership_id]
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to dealership_path(@dealership), notice: 'Car was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @dealership = Dealership.find params[:dealership_id]
    @car.destroy
    respond_to do |format|
      format.html { redirect_to dealership_path(@dealership), notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sell_car
    @dealership = Dealership.find params[:dealership_id]
    # @car = Car.find params[:id]
    @car.sell!
    redirect_to cars_url
  end

  def reserve
    @dealership = Dealership.find params[:dealership_id]
    @car.reserve!
    redirect_to cars_url
  end

  def reneg
    @dealership = Dealership.find params[:dealership_id]
    @car.reneg!
    redirect_to cars_url
  end

  def create_comment
    @dealership = Dealership.find params[:dealership_id]
    @car = @dealership.cars.find params[:id]
    @comment = @car.comments.create comment_params
    redirect_to dealership_car_path(@dealership, @car)
  end

  def delete_comment
    p params
    @dealership = Dealership.find params[:dealership_id]
    @car = @dealership.cars.find params[:id]
    @comment = @car.comments.find params[:comment_id]
    @comment.delete
    redirect_to dealership_car_path(@dealership, @car)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # def set_dealership
    #   @dealership = Dealership.find params[:dealership_id]
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:make, :model, :year)
    end
  
    def comment_params
      params.require(:comment).permit(:content)
    end

end

app/controllers/dealerships_controller.rb
class DealershipsController < ApplicationController
  def index
    @dealerships = Dealership.all
  end

  def show
    @dealership = Dealership.find params[:id]
    @comment = @dealership.comments.new
  end

  def new
    @dealership = Dealership.new
  end

  def create
    @dealership = Dealership.create dealership_params
    redirect_to dealerships_path
  end

  def edit
    @dealership = Dealership.find params[:id]
  end

  def update
    @dealership = Dealership.find params[:id]
    @dealership.update_attributes dealership_params
    redirect_to dealerships_path
  end

  def destroy
    @dealership = Dealership.find params[:id]
    @dealership.delete
    redirect_to dealerships_path
  end

  def create_comment
    @dealership = Dealership.find params[:id]
    @dealership.comments.create comment_params
    # dealership_path(@dealership)
    redirect_to @dealership
  end

  def delete_comment
    @dealership = Dealership.find params[:id]
    @comment = Comment.find params[:comment_id]
    @comment.delete
    redirect_to @dealership
  end
private
  def dealership_params
    params.require(:dealership).permit(:name, :description)
  end

  # Whitelisting parameters
  # Strong params - In rails
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @hello_world = "Ben you look confused."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/dealerships_helper.rb
module DealershipsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cars/_form.html.haml
= form_for [@dealership, @car] do |f|
  - if @car.errors.any?
    #error_explanation
      %h2= "#{pluralize(@car.errors.count, "error")} prohibited this car from being saved:"
      %ul
        - @car.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :make
    = f.text_field :make
  .field
    = f.label :model
    = f.text_field :model
  .field
    = f.label :year
    = f.number_field :year
  .actions
    = f.submit 'Save'

app/views/cars/edit.html.haml
%h1 Editing car

= render 'form'

= link_to 'Back', dealership_path(@dealership)

app/views/cars/index.html.haml
%h1 Listing cars

%table
  %tr
    %th Make
    %th Model
    %th Year
    %th Workflow State
    %th
    %th
    %th
    %th Change State

  - @cars.each do |car|
    %tr
      %td= car.make
      %td= car.model
      %td= car.year
      %td= car.workflow_state
      %td= link_to 'Show', car
      %td= link_to 'Edit', edit_car_path(car)
      %td
        = link_to 'Destroy', car, :method => :delete, :data => { :confirm => 'Are you sure?' }
      %td.workflow_state
        - if car.workflow_state != "sold"
          = link_to "Sell!", sell_car_car_path(car), method: :put
        - if !['reserved', 'sold'].include?(car.workflow_state)
          = link_to "Reserve!", reserve_car_path(car), method: :put
        - if !['for_sale', 'sold'].include?(car.workflow_state)
          = link_to "Reneg!", reneg_car_path(car), method: :put

%br

= link_to 'New Car', new_car_path

app/views/cars/new.html.haml
%h1 New car

= render 'form'

= link_to 'Back', dealerships_path(@dealership)

app/views/cars/show.html.haml
%p
  %strong Make:
  = @car.make
%p
  %strong Model:
  = @car.model
%p
  %strong Year:
  = @car.year
%p
  %strong Dealership
  / = @car.dealership_id
  - if @car.dealership
    / @car.dealership
    = link_to @dealership.try(:name), dealership_path(@dealership)

/ @car.dealership
= link_to 'Back', dealership_path(@dealership)
%br
%ul
  - @car.comments.each do |comment|
    - if comment.content
      %li
        = comment.content
        = link_to "[Delete]", delete_comment_dealership_car_path(@dealership, @car, comment_id: comment.id, john_hammond: "not from jurrasic park"), method: :delete

= form_for @comment, url: create_comment_dealership_car_path(@dealership, @car) do |f|
  = f.label :content
  = f.text_area :content
  %br
  = f.submit

app/views/dealerships/_form.html.haml
= form_for @dealership do |f|
  = f.label :name
  = f.text_field :name
  %br
  = f.label :description
  = f.text_field :description
  %br
  = f.submit

app/views/dealerships/edit.html.haml
%h1 Edit Dealership

= render 'form'

app/views/dealerships/index.html.haml
%h1 Dealerships

= link_to "Create Dealership", new_dealership_path
%ul
  - @dealerships.each do |dealership|
    %li
      %strong
        = link_to dealership.name, dealership_path(dealership)
      = dealership.description
      |
      = link_to "Edit", edit_dealership_path(dealership)
      |
      = link_to "Delete", dealership_path(dealership), method: :delete
= link_to "Back", root_path

app/views/dealerships/new.html.haml
%h1 New Dealership

= render 'form'

app/views/dealerships/show.html.haml
%h1 Show Dealership
%strong
  Name:
= @dealership.name
%br
%strong
  Description
= @dealership.description
%br
= link_to "Create Car", new_dealership_car_path(@dealership)
%ul
  /= @dealership.cars.inspect
  - @dealership.cars.each do |car|
    %li
      = link_to "#{car.make} | #{car.model}", dealership_car_path(@dealership, car)
      |
      = link_to "Edit", edit_dealership_car_path(@dealership, car)
      |
      = link_to "Delete", dealership_car_path(@dealership, car), method: :delete

%br
= link_to "Back", dealerships_path
%br
Comments
%br
%ul
  - @dealership.comments.each do |comment|
    - if comment.content
      %li
        = comment.content
        = link_to "[Delete]", delete_comment_dealership_path(@dealership, comment_id: comment.id), method: :delete

= form_for @comment, url: create_comment_dealership_path(@dealership) do |f|
  = f.label :content
  = f.text_area :content
  %br
  = f.submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Carlot
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %p
    #notice
      = flash[:notice]
      = flash[:error]
    = yield

app/views/welcome/index.html.haml
%h1 Welcome#index
%h2 
  Hello world
  %br
  asdf

%div.item#asdf
  Find me in app/views/welcome/index.html.haml
  %ul
    %li Some text
    %li Some more text
    %li Some more more text
  =@hello_world
  - if 1+1==2
    Some text
  - 10.times do |x|
    asdf
    = x

= link_to "Dealerships", dealerships_path